package processors

import (
	"fmt"

	pgs "github.com/lyft/protoc-gen-star/v2"
)

func Version(version string) pgs.PostProcessor {
	return &appVersionProcessor{version}
}

type appVersionProcessor struct {
	version string
}

func (p *appVersionProcessor) Match(a pgs.Artifact) bool {
	switch a.(type) {
	case pgs.CustomFile, pgs.CustomTemplateFile:
		return true
	default:
		return false
	}
}

func (p *appVersionProcessor) Process(in []byte) ([]byte, error) {
	return []byte(fmt.Sprintf(`// Code generated by mpt-code-gen. DO NOT EDIT.
// version v%s
%s`, p.version, in)), nil
}
