package config

const fileTpl = `// Code generated by protoc-gen-code. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

import (
	"github.com/caarlos0/env/v10"
	"github.com/joho/godotenv"
)
{{ range .AllMessages }}
{{ if enabled .}}
{{ cmt "config struct for " (name .) }}
{{ template "struct" . }}
{{ template "function" . }}
{{ end }}
{{ end }}
`
